#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# brew install coreutils
# echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
# brew install findutils
# Install Bash 4
# brew install bash

# Install wget with IRI support
brew install wget --enable-iri

# Install other useful binaries
brew install ack
# brew install imagemagick
brew install node
brew install rename
brew install webkit2png
brew install git-ftp

# Remove outdated versions from the cellar
brew cleanup
