#!/bin/zsh

run_npm() {

    # Check for npm
    if type_exists 'npm'; then
        e_header "Installing Node.js packages..."

        # List of npm packages
		# Many of these are LSPs for use with nvim
        local packages="stylelint-lsp svelte-language-server @tailwindcss/language-server tiddlywiki typescript-language-server vscode-langservers-extracted"

        # Install packages globally and quietly
        npm install $packages --global --quiet

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit
    fi

}
