#!/bin/zsh

source ./lib/utils

# Check for npm - CURRENTLY BROKEN? not sure why, so we bypass the check
# if type_exists 'npm'; then
	e_header "Installing Node.js packages..."

	# List of npm packages
	# Many of these are LSPs for use with nvim
	local packages=(
		'stylelint-lsp' 
		'svelte-language-server' 
		'@tailwindcss/language-server' 
		'tiddlywiki' 
		'typescript'
		'typescript-language-server' 
		'vscode-langservers-extracted'
	)

	# Install packages globally
	npm install -g $packages

	[[ $? ]] && e_success "Done"
# else
# 	printf "\n"
# 	e_error "Error: npm not found."
# 	printf "Aborting...\n"
# 	exit
# fi
