#!/bin/zsh

# Set to run directly via ./lib/npm
# Rerun everytime you reset a global node version via asdf

source $(dirname $0)/utils

e_header "Checking npm..."

# List of global npm packages
# Many of these are LSPs for use with nvim
local packages=(
  'degit'
  'stylelint-lsp'
  'svelte-language-server'
  '@tailwindcss/language-server'
  'tiddlywiki'
  'typescript'
  'typescript-language-server'
  'vscode-langservers-extracted'
  '@astrojs/language-server'
)

# Install packages globally
npm install -g $packages
