#!/bin/bash

run_rvm() {

    # Check for npm
    if type_exists 'rvm'; then
        e_header "Installing Ruby gems..."

        # List of npm packages
        local gems="compass boom"

        # Install gems quietly
        gem install $gems --quiet

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_error "Error: rvm not found."
        printf "Aborting...\n"
        exit
    fi

}
