# bash_aliases

# self managing aliases - point to dotfile scripts
alias dot_uninstall="bash ~/.dotfiles/bin/uninstall.sh"
alias dot_nuke="bash ~/.dotfiles/bin/nuke.sh"

# Basic navigation
alias ..='cd ..'
alias ...="cd ../.."
alias ....="cd ../../.."
alias ~="cd ~"
alias -- -="cd -"

# Fancy lists
alias ll='ls -laF'       # long form, everything
alias lo='ls -oG'        # long form, no user group, no hidden
alias lt='ls -toaG'      # order by last modified, everything
alias lf='ls -AGFoh'     # long form, no user, file size

# Shortcuts
alias a="ack -ia"        # ack everything, case insensitive
alias catn='cat -n'      # join and print with line numbers
alias zz='exit'          # quick exit
alias mvp='mvim -p'      # open all files in macvim tabs
alias mvd='mvim -d'      # open mvim with diff splits
alias mm="mvim; middleman" # Open mvim then start middleman
alias mg="mvim; gulp"    # Open mvim then start gulp
alias sudo='sudo '       # Enable aliases to be sudo’ed
alias o="open"           # Open file with default application
alias oo="open ."        # Open cd in Finder

# IP Addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias localip0="ipconfig getifaddr en0"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache"

# System monitoring
alias toc="top -o cpu"
alias tor="top -o rsize"

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
# (useful when executing time-consuming commands)
alias badge="tput bel"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Get OS X Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; npm update npm -g; npm update -g; sudo gem update'

# Show/hide hidden files in Finder
alias show="defaults write com.apple.Finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.Finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
