# bash_profile

declare -a files=(
    $HOME/.dotfiles/bash/bash_options # Options
    $HOME/.dotfiles/bash/bash_exports # Exports
    $HOME/.dotfiles/bash/bash_aliases # Aliases
    $HOME/.dotfiles/bash/bash_functions # Functions
    $HOME/.dotfiles/bash/bash_prompt # Custom bash prompt
    $HOME/.bashrc.local # Local and private settings not under version control (e.g. git credentials)
    $HOME/.dotfiles/bash/bash_paths # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
    $HOME/.dotfiles/bin/bashmarks.sh # Bookmark utility
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 
